version: '3.8'

services:
  app:
    container_name: crypto.app
    build:
      context: ./.docker/php
    entrypoint: [ "bash", "-c", "
          until php bin/console doctrine:query:sql 'SELECT 1'; do sleep 2; done;
          php bin/console doctrine:migrations:migrate --no-interaction;
          php bin/console run:sync-rates;
          php-fpm
        " ]
    volumes:
      - .:/var/www/crypto
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    ports:
      - "9003:9003"  # Откроем порт Xdebug наружу
    working_dir: /var/www/crypto
    depends_on:
      - db
    environment:
      - APP_ENV=dev

  nginx:
    container_name: crypto.nginx
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/crypto
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    container_name: crypto.db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: crypto
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"

  redis:
    container_name: crypto.redis
    image: redis:latest
    ports:
      - "6379:6379"

  cron:
    build:
      context: ./.docker/cron
    container_name: crypto.cron
    depends_on:
      - app
    volumes:
      - .:/var/www/crypto